#include<cstdint>
#include<vector>
#include<complex>
using ll=long long;using ull=unsigned long long;using ld=long double;using cpx=std::complex<double>;using std::vector;
#include<valarray>
#include<algorithm>
#include<cmath>
using std::vector;using std::valarray;static vector<cpx>w_fft;vector<cpx>&fft_init(int n){if(w_fft.empty())w_fft={1};while((int)w_fft.size()<n){int m=(int)w_fft.size();double ang=2*PI/(m*2);cpx wn(cos(ang),sin(ang));w_fft.resize(m*2);for(int i=m;i<m*2;i++)w_fft[i]=wn*w_fft[i^m];}return w_fft;}valarray<cpx>fft_dif(const vector<cpx>&src,int n){auto&w=fft_init(n);valarray<cpx>a(cpx(0),n);std::copy(src.begin(),src.end(),&a[0]);for(int len=n,k=n>>1;k>=1;len>>=1,k>>=1){for(int i=0,t=0;i<n;i+=len,t++){for(int j=0;j<k;j++){auto x=a[i+j];auto y=a[i+j+k]*w[t];a[i+j]=x+y;a[i+j+k]=x-y;}}}return a;}vector<cpx>fft_dit(const valarray<cpx>&src){int n=(int)src.size();auto&w=fft_init(n);vector<cpx>a(begin(src),end(src));for(int k=1,len=2;len<=n;k<<=1,len<<=1){for(int i=0,t=0;i<n;i+=len,t++){for(int j=0;j<k;j++){auto x=a[i+j];auto y=a[i+j+k];a[i+j]=x+y;a[i+j+k]=(x-y)*w[t];}}}for(int i=0;i<n;i++)a[i]/=n;std::reverse(a.begin()+1,a.end());return a;}vector<cpx>fft_mul(const vector<cpx>&a,const vector<cpx>&b){int need=(int)a.size()+(int)b.size()-1;int len=glim(need);auto A=fft_dif(a,len);auto B=fft_dif(b,len);A*=B;auto c=fft_dit(A);c.resize(need);return c;}vector<cpx>fft_conv(vector<cpx>a,const vector<cpx>&b){std::reverse(a.begin(),a.end());int len=glim(a.size()+b.size()-1);auto A=fft_dif(a,len);auto B=fft_dif(b,len);A*=B;auto c=fft_dit(A);c.erase(c.begin(),c.begin()+a.size()-1);c.resize(b.size()-a.size()+1);return c;}template<int MOD>struct mint{int v;mint(ll v_=0):v(int(v_%MOD)){if(v<0)v+=MOD;}friend mint operator+(mint a,mint b){int r=a.v+b.v;return r>=MOD?r-MOD:r;}friend mint operator-(mint a,mint b){int r=a.v-b.v;return r<0?r+MOD:r;}friend mint operator*(mint a,mint b){return(ll)a.v*b.v%MOD;}mint&operator+=(mint b){return*this=*this+b;}mint&operator-=(mint b){return*this=*this-b;}mint&operator*=(mint b){return*this=*this*b;}mint pow(ll k)const{mint r=1,a=*this;for(;k;k>>=1,a*=a)if(k&1)r*=a;return r;}mint inv()const{return pow(MOD-2);}bool operator==(mint b)const{return v==b.v;}bool operator!=(mint b)const{return v!=b.v;}};
#include<cstddef>
using std::vector;using std::valarray;constexpr int NTT_MOD=998244353;using mint=mint<NTT_MOD>;inline int glim(size_t x){return x==1?1:2<<(31^__builtin_clz((int)x-1));}static vector<mint>wt;vector<mint>&ntt_init(int n){if(wt.empty())wt={1};while((int)wt.size()<n){int m=(int)wt.size();mint wn=mint(3).pow((NTT_MOD-1)/m>>2);wt.resize(m<<1);for(int i=m;i<m<<1;i++)wt[i]=wn*wt[i^m];}return wt;}valarray<mint>ntt_dif(const vector<mint>&src,int n){auto&w=ntt_init(n);valarray<mint>a(mint(0),n);std::copy(src.begin(),src.end(),&a[0]);for(int len=n,k=n>>1;k>=1;len>>=1,k>>=1){for(int i=0,t=0;i<n;i+=len,t++){for(int j=0;j<k;j++){auto x=a[i+j];auto y=a[i+j+k]*w[t];a[i+j]=x+y;a[i+j+k]=x-y;}}}return a;}vector<mint>ntt_dit(const valarray<mint>&src){int n=(int)src.size();auto&w=ntt_init(n);vector<mint>a(begin(src),end(src));for(int k=1,len=2;len<=n;k<<=1,len<<=1){for(int i=0,t=0;i<n;i+=len,t++){for(int j=0;j<k;j++){auto x=a[i+j];auto y=a[i+j+k];a[i+j]=x+y;a[i+j+k]=(x-y)*w[t];}}}mint inv_n=mint::mod-(mint::mod-1)/n;for(int i=0;i<n;i++)a[i]*=inv_n;std::reverse(a.begin()+1,a.end());return a;}vector<mint>ntt_mul(const vector<mint>&a,const vector<mint>&b){int need=(int)a.size()+(int)b.size()-1;int len=glim(need);auto A=ntt_dif(a,len);auto B=ntt_dif(b,len);A*=B;auto c=ntt_dit(A);c.resize(need);return c;}vector<mint>ntt_conv(vector<mint>a,const vector<mint>&b){std::reverse(a.begin(),a.end());int len=glim(a.size()+b.size()-1);auto A=ntt_dif(a,len);auto B=ntt_dif(b,len);A*=B;auto c=ntt_dit(A);c.erase(c.begin(),c.begin()+a.size()-1);c.resize(b.size()-a.size()+1);return c;}
